env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  import/no-extraneous-dependencies: off
  import/no-unresolved: off
  react/jsx-filename-extension: off
  react/prop-types: off